spring.application.name=StyleAura


server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/styleaura_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#"token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vQGdtYWlsLmNvbSIsImlhdCI6MTc4NTYwMjc4MywiZXhwIjoxNzg1Njg5MTgzfQ._bfly1cv3Xb7gnp7yvWquRkQziWPQVyL_zCnUSPir64",